In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
sns.set

In [2]:
w_happiness = pd.read_csv('2017.csv')
w_economic = pd.read_csv('economic_freedom_index2019_data.csv',  encoding='latin-1')
w_human = pd.read_csv('hfi_cc_2018.csv')
gdp = pd.read_csv('API_NY.GDP.PCAP.PP.CD_DS2_en_csv_v2_41041.csv', skiprows=3)
gini = pd.read_csv('API_SI.POV.GINI_DS2_en_csv_v2_41010.csv', skiprows=3)

In [3]:
w_happiness = w_happiness[['Country', 'Happiness.Rank', 'Happiness.Score']]
w_happiness.head(3)
#Y = 2017

   Country  Happiness.Rank  Happiness.Score
0   Norway               1            7.537
1  Denmark               2            7.522
2  Iceland               3            7.504

In [4]:
w_economic = w_economic[['Country Name','World Rank', 'Unemployment (%)', 'GDP Growth Rate (%)', '2019 Score']].sort_values('World Rank').reset_index(drop = True)
w_economic.head(3)
#Y = 2019

  Country Name  World Rank Unemployment (%)  GDP Growth Rate (%)  2019 Score
0    Hong Kong         1.0              3.1                  3.8        90.2
1    Singapore         2.0              2.0                  3.6        89.4
2  New Zealand         3.0              4.9                  3.0        84.4

In [5]:
w_human = w_human[['countries', 'hf_rank', 'hf_score',]].loc[w_human['year'] == 2016].sort_values('hf_rank').reset_index(drop = True)
w_human.head(3)
#Y = 2016

     countries  hf_rank  hf_score
0  New Zealand      1.0  8.887410
1  Switzerland      2.0  8.787759
2    Hong Kong      3.0  8.776840

In [6]:
gdp = gdp[['Country Name', '2018']]
gdp = gdp.dropna()
gdp = gdp.astype({"Country Name": object, "2018": int})
gdp.head(3)

  Country Name   2018
1  Afghanistan   1951
2       Angola   6440
5   Arab World  17557

In [7]:
gini =gini[['Country Name','2010']]
gini = gini.dropna().reset_index(drop = True)
gini.head(3)
#Y = 2010

  Country Name  2010
0    Argentina  43.0
1      Armenia  30.0
2    Australia  34.7

In [8]:
merge1 = pd.merge(w_happiness, w_economic, how='left', left_on=['Country'], right_on=['Country Name'])
merge1 = merge1.dropna()
merge1.head()

,Country,Happiness.Rank,Happiness.Score,Country Name,World Rank,Unemployment (%),GDP Growth Rate (%),2019 Score
0,Norway,1,7.537,Norway,26.0,4.2,1.8,73.0
1,Denmark,2,7.522,Denmark,14.0,5.7,2.1,76.7
2,Iceland,3,7.504,Iceland,11.0,2.8,3.6,77.1
3,Switzerland,4,7.494,Switzerland,4.0,4.8,1.1,81.9
4,Finland,5,7.469,Finland,20.0,8.6,3.0,74.9

In [9]:
merge2 = pd.merge(merge1, w_human, how='left', left_on=['Country Name'], right_on=['countries'])
merge2.head()

,Country,Happiness.Rank,Happiness.Score,Country Name,World Rank,Unemployment (%),GDP Growth Rate (%),2019 Score,countries,hf_rank,hf_score
0,Norway,1,7.537,Norway,26.0,4.2,1.8,73.0,Norway,10.0,8.471241
1,Denmark,2,7.522,Denmark,14.0,5.7,2.1,76.7,Denmark,6.0,8.547820
2,Iceland,3,7.504,Iceland,11.0,2.8,3.6,77.1,Iceland,27.0,8.151753
3,Switzerland,4,7.494,Switzerland,4.0,4.8,1.1,81.9,Switzerland,2.0,8.787759
4,Finland,5,7.469,Finland,20.0,8.6,3.0,74.9,Finland,10.0,8.472184

In [10]:
merge3 = pd.merge(merge2, gdp, how='left', left_on=['Country Name'], right_on=['Country Name'])
merge3 = merge3.dropna().drop('Country', axis = 1)
merge3.head()

,Happiness.Rank,Happiness.Score,Country Name,World Rank,Unemployment (%),GDP Growth Rate (%),2019 Score,countries,hf_rank,hf_score,2018
0,1,7.537,Norway,26.0,4.2,1.8,73.0,Norway,10.0,8.471241,63756.0
1,2,7.522,Denmark,14.0,5.7,2.1,76.7,Denmark,6.0,8.547820,56120.0
2,3,7.504,Iceland,11.0,2.8,3.6,77.1,Iceland,27.0,8.151753,57597.0
3,4,7.494,Switzerland,4.0,4.8,1.1,81.9,Switzerland,2.0,8.787759,68943.0
4,5,7.469,Finland,20.0,8.6,3.0,74.9,Finland,10.0,8.472184,48635.0

In [11]:
final_tab = pd.merge(merge3, gini, how='left', left_on=['Country Name'], right_on=['Country Name'])
final_tab = final_tab.rename(columns={"Country Name": "country", "2010": "gini", "2018": "gdp_ppp","Happiness.Rank": "h_rank","Happiness.Score": "h_score","World Rank": "ef_rank", "GDP Growth Rate (%)": "growth_rate", "Unemployment (%)": "unemployment", '2019 Score':'ef_score'})
final_tab = final_tab.drop('countries', axis = 1)

In [12]:
final_tab = final_tab[['country', 'h_rank', 'hf_rank', 'ef_rank', 'h_score', 'ef_score', 'hf_score',
       'gini', 'unemployment', 'growth_rate', 'gdp_ppp']]
final_tab = final_tab.dropna().reset_index(drop = True)
final_tab['ef_score'] = final_tab['ef_score']/10
final_tab.sort_values('ef_rank')

,country,h_rank,hf_rank,ef_rank,h_score,ef_score,hf_score,gini,unemployment,growth_rate,gdp_ppp
3,Switzerland,4,2.0,4.0,7.494,8.19,8.787759,32.6,4.8,1.1,68943.0
8,Australia,10,4.0,5.0,7.284,8.09,8.582219,34.7,5.6,2.3,51544.0
13,Ireland,15,8.0,6.0,6.977,8.05,8.504565,32.3,6.4,7.8,84069.0
17,United Kingdom,19,8.0,7.0,6.714,7.89,8.497918,34.4,4.3,1.8,46239.0
6,Canada,7,5.0,8.0,7.316,7.77,8.565863,33.6,6.3,3.0,47870.0
2,Iceland,3,27.0,11.0,7.504,7.71,8.151753,26.2,2.8,3.6,57597.0
12,United States,14,17.0,12.0,6.993,7.68,8.388655,40.4,4.4,2.3,62641.0
5,Netherlands,6,6.0,13.0,7.377,7.68,8.554421,27.8,4.8,3.1,56772.0
1,Denmark,2,6.0,14.0,7.522,7.67,8.547820,27.2,5.7,2.1,56120.0
34,Estonia,66,14.0,15.0,5.611,7.66,8.436851,32.0,5.8,4.9,35747.0
55,Georgia,125,40.0,16.0,4.286,7.59,7.798268,39.5,11.6,4.8,11420.0
16,Luxembourg,18,15.0,17.0,6.863,7.59,8.428701,30.5,5.5,3.5,111908.0
7,Sweden,9,17.0,19.0,7.284,7.52,8.387375,27.7,6.7,2.4,53119.0
4,Finland,5,10.0,20.0,7.469,7.49,8.472184,27.7,8.6,3.0,48635.0
14,Germany,16,13.0,24.0,6.951,7.35,8.462596,30.2,3.8,2.5,54327.0
0,Norway,1,10.0,26.0,7.537,7.30,8.471241,25.7,4.2,1.8,63756.0
9,Israel,11,49.0,27.0,7.213,7.28,7.517458,42.6,4.3,3.3,40786.0
11,Austria,13,16.0,31.0,7.006,7.20,8.413474,30.3,5.5,2.9,56253.0
60,Rwanda,151,71.0,32.0,3.471,7.11,6.973870,47.2,1.3,6.1,2253.0
20,Uruguay,28,43.0,40.0,6.454,6.86,7.728071,44.5,7.9,3.1,23530.0
23,Thailand,32,98.0,43.0,6.424,6.83,6.624781,39.4,1.1,3.9,19017.0
33,Peru,63,47.0,45.0,5.715,6.78,7.575393,45.5,3.6,2.5,14393.0
28,Poland,46,39.0,46.0,5.973,6.78,7.811560,33.2,4.9,4.6,32356.0
54,Armenia,121,57.0,47.0,4.376,6.77,7.241402,30.0,18.2,7.5,10324.0
15,Belgium,17,27.0,48.0,6.891,6.73,8.153589,28.4,7.4,1.7,50774.0
25,Colombia,36,87.0,49.0,6.357,6.73,6.760757,54.7,8.9,1.8,14999.0
21,Panama,30,46.0,50.0,6.452,6.72,7.647620,51.6,4.5,5.4,25508.0
38,Jordan,74,75.0,53.0,5.336,6.65,6.849333,33.7,14.9,2.3,9347.0
42,Indonesia,81,85.0,56.0,5.262,6.58,6.770656,36.4,4.2,5.1,13056.0
24,Spain,34,25.0,57.0,6.403,6.57,8.159107,35.2,17.2,3.1,40854.0
...,...,...,...,...,...,...,...,...,...,...,...
31,Kazakhstan,60,90.0,59.0,5.819,6.54,6.742838,28.0,4.9,4.0,27830.0
10,Costa Rica,12,37.0,61.0,7.079,6.53,7.857714,48.2,8.1,3.2,17645.0
44,Portugal,89,22.0,62.0,5.195,6.53,8.276856,35.8,8.9,2.7,34065.0
39,Hungary,75,42.0,64.0,5.324,6.50,7.739473,29.4,4.2,4.0,30978.0
19,Mexico,25,75.0,66.0,6.578,6.47,6.848010,45.3,3.4,2.0,19969.0
36,Turkey,69,107.0,68.0,5.500,6.46,6.466233,38.8,11.3,7.0,28815.0
22,France,31,32.0,71.0,6.442,6.38,8.008401,33.7,9.4,1.8,45877.0
29,Italy,48,34.0,80.0,5.964,6.22,7.980223,34.7,11.2,1.5,42080.0
27,El Salvador,45,70.0,84.0,6.003,6.18,7.033951,43.5,4.5,2.4,8316.0
37,Paraguay,70,72.0,85.0,5.493,6.18,6.962299,51.0,4.6,4.3,13570.0
45,Honduras,91,92.0,93.0,5.181,6.02,6.723241,53.1,4.5,4.8,5129.0
30,Moldova,56,75.0,97.0,5.838,5.91,6.849515,32.1,4.5,4.0,7300.0
40,China,79,135.0,100.0,5.273,5.84,5.905410,43.7,4.7,6.9,18210.0
49,South Africa,101,63.0,102.0,4.829,5.83,7.172572,63.4,27.3,1.3,13661.0
35,Belarus,67,128.0,104.0,5.569,5.79,6.144514,28.6,0.5,2.4,19959.0
43,Greece,87,61.0,106.0,5.227,5.77,7.203384,34.1,21.5,1.4,29873.0
59,Madagascar,144,103.0,114.0,3.644,5.66,6.512562,42.4,1.8,4.1,1634.0
51,Bangladesh,110,138.0,121.0,4.608,5.56,5.801300,32.1,4.4,7.1,4364.0
50,Tunisia,102,109.0,125.0,4.805,5.54,6.433736,35.8,15.4,1.9,12483.0
48,Mongolia,100,45.0,126.0,4.955,5.54,7.699156,33.1,7.0,5.1,13735.0
46,Vietnam,94,124.0,128.0,5.074,5.53,6.194004,39.3,2.1,6.8,7434.0
41,Pakistan,80,140.0,131.0,5.269,5.50,5.662296,29.8,4.0,5.3,5543.0
47,Nepal,99,92.0,136.0,4.962,5.38,6.720806,32.8,2.7,7.5,3064.0
53,Ethiopia,119,150.0,137.0,4.460,5.36,5.397045,33.2,5.2,10.9,2018.0
52,Zambia,116,116.0,138.0,4.514,5.36,6.308849,55.6,7.8,3.6,4216.0
58,Lesotho,139,100.0,142.0,3.808,5.31,6.534222,54.2,27.3,3.1,3223.0
56,Ukraine,132,118.0,147.0,4.096,5.23,6.283135,24.8,9.5,2.5,9233.0
18,Argentina,24,107.0,148.0,6.599,5.22,6.469848,43.0,8.7,2.9,20567.0
57,Malawi,136,97.0,153.0,3.970,5.14,6.652607,45.5,5.9,4.0,1308.0
26,Ecuador,44,83.0,170.0,6.008,4.69,6.805278,48.7,3.8,2.7,11713.0

In [13]:
corr = final_tab.corr()
corr.style.background_gradient(cmap='coolwarm')

In [14]:
final_tab.to_csv("final_tab.csv")
final_tab.columns

Index(['country', 'h_rank', 'hf_rank', 'ef_rank', 'h_score', 'ef_score',
       'hf_score', 'gini', 'unemployment', 'growth_rate', 'gdp_ppp'],
      dtype='object')

In [15]:
work = pd.read_csv('/home/javier/Documents/ironhack_projects/final_tab.csv')[['country', 'h_score', 'ef_score',
       'hf_score', 'gini', 'unemployment', 'gdp_ppp']]

FileNotFoundError: [Errno 2] File b'/home/javier/Documents/ironhack_projects/final_tab.csv' does not exist: b'/home/javier/Documents/ironhack_projects/final_tab.csv'

In [ ]:
work

In [ ]:
corr = work.corr()
corr.style.background_gradient(cmap='coolwarm')

In [ ]:
sns.set(style="ticks")
plt.figure(figsize=(8, 6))
sns.heatmap(work.corr(), annot=True, fmt=".2f")
plt.show()

In [ ]:
sns.set()
plt.figure(figsize=(20, 15))
sns.regplot("gdp_ppp", "gini", data=work, color="k", label='Gini index')

plt.show()

In [ ]:
plt.figure(figsize = (16,12))
sns.regplot("gdp_ppp", "h_score", data=work, color="g", label = 'Happiness')
#sns.regplot("gdp_ppp", "hf_score", data=work, color="c", label = 'Social freedom', scatter = False)
#sns.regplot("gdp_ppp", "ef_score", data=work, color="r", label = 'Economic Freedom', scatter = False)

plt.show()

In [ ]:
f, ax = plt.subplots(figsize = (16,12))
ax.set(xlim=(0, 120000), ylim=(5, 10))
sns.regplot("gdp_ppp", "h_score", data=work, color="g", label = 'Happiness', scatter=False)
sns.regplot("gdp_ppp", "hf_score", data=work, color="c", label = 'Social freedom', scatter = False)
sns.regplot("gdp_ppp", "ef_score", data=work, color="r", label = 'Economic Freedom', scatter = False)

In [ ]:
sns.set()
plt.figure(figsize=(16, 12))
#sns.regplot("h_score", "h_score", data=work, color="m", label = 'Happiness')
sns.regplot("h_score", "hf_score", data=work, color="c", label = 'Social freedom')
sns.regplot("h_score", "ef_score", data=work, color="red", label = 'Economic Freedom')
plt.legend()
plt.show()

In [ ]:
sns.set()
plt.figure(figsize=(16, 12))
sns.regplot("ef_score", "h_score", data=work, color="g", label = 'Happiness')
sns.regplot("ef_score", "hf_score", data=work, color="c", label = 'Social freedom')
#sns.regplot("ef_score", "ef_score", data=work, color="r", label = 'Economic Freedom')
plt.legend()
plt.show()

In [ ]:
sns.set()
plt.figure(figsize=(16, 12))
sns.regplot("hf_score", "h_score", data=work, color="g",  label = 'Happiness')
#sns.regplot("hf_score", "hf_score", data=work, color="darkcyan", label = 'Social freedom')
sns.regplot("hf_score", "ef_score", data=work, color="red", label = 'Economic Freedom')
plt.legend()
plt.show()